### ISSUE TITLE
Petaca official has migrated to github

### ISSUE THREAD

**Issue by zbeekman** [certik/petaca#4]
Hi,
I just wanted to make sure you knew that @nncarlson has migrated the official Petaca hosting to github: https://github.com/nncarlson/petaca

It might be worthwhile to fork this repository directly, since right now the page rank of Petaca search results on google lists this repo as the first hit.

**Comment by certik** [comment]
@zbeekman yes, I am very happy that @nncarlson did that. I'll fork and repost my patches as PRs to his repository.

**Comment by zbeekman** [comment]
Cool, closing this now...
